name: Deploy on Main

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3 
      - name: Setup
        run: echo "Assigning Environment Variables"
      - name: Login to EC2
        run: |
          echo "Running on EC2"

      - name: Get New Source Code
        run: |
          cd ~/thinkingaujus &&
          git checkout main &&
          git fetch --all &&
          git reset --hard origin/main &&
          git pull origin main

      - name: Build and run docker
        run: |
          docker-compose down &&
          docker-compose build &&
          docker-compose up -d
