name: Deploy on Main

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 
      - name: Setup
        run: echo "Assigning Environment Variables"
      - name: Login to EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -T -i private_key ${USER_NAME}@${HOSTNAME}

      - name: Get New Source Code
        run: |
          cd ~/thinkingaujus &&
          git checkout main &&
          git fetch --all &&
          git reset --hard origin/main &&
          git pull origin main

      - name: Build and run docker
        run: |
          docker-compose down &&
          docker-compose build &&
          docker-compose up -d
